I have performed the Suggested Fix and continue to receive this error. If I am posting this message without having performed the Suggested Fix I am aware that I am consuming the Developer(s) time in managing my Issue unnecessarily.

== Version: 4.1.3.0 ==

== Error Message ==
An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
Index was outside the bounds of the array.

== StackTrace ==
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Rawr.UI.OptimizeWindow.optimizer_ComputeUpgradesCompleted(Object sender, ComputeUpgradesCompletedEventArgs e)
   at Rawr.Optimizer.ItemInstanceOptimizer.OnComputeUpgradesCompleted(ComputeUpgradesCompletedEventArgs e)
   at Rawr.Optimizer.ItemInstanceOptimizer.PrivateComputeUpgradesCompleted(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)


